# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zlaeo1JkZjwnbyP5WHa2Yj6AxvYOxvSL
"""

"""
Flask Backend API — Smart Grid RL Dashboard
CT-469 Reinforcement Learning Project

Endpoints:
    GET  /api/status          — Health check + model status
    POST /api/step            — Run one simulation step with given state
    POST /api/run-episode     — Run a full 24-hour episode
    GET  /api/training-log    — Return training metrics for charts
    GET  /api/compare         — Run baseline comparison and return results
    POST /api/custom-scenario — Run episode with user-defined starting conditions
"""

import os
import sys
import json
import numpy as np
from flask import Flask, request, jsonify
from flask_cors import CORS

# ---- resolve imports whether run from /backend or project root ----
sys.path.insert(0, os.path.dirname(__file__))
from environment import SmartGridEnv
from dqn_agent   import DQNAgent
from baseline    import RuleBasedAgent, RandomAgent, DoNothingAgent, evaluate_agent

app = Flask(__name__)
CORS(app)   # Allow frontend on different port to call API

# ---- Global objects (loaded once at startup) ----------------------
MODEL_PATH   = os.path.join(os.path.dirname(__file__), "models", "dqn_model.pth")
LOG_PATH     = os.path.join(os.path.dirname(__file__), "logs",   "training_log.json")
DATA_PATH    = os.path.join(os.path.dirname(__file__), "data",   "energy_dataset.csv")

# Use real data if available, else synthetic
data_path = DATA_PATH if os.path.exists(DATA_PATH) else None
env   = SmartGridEnv(data_path=data_path, episode_length=24, seed=42)
agent = DQNAgent(state_dim=6, action_dim=4)

model_loaded = False
if os.path.exists(MODEL_PATH):
    try:
        agent.load(MODEL_PATH)
        model_loaded = True
        print("[API] Pre-trained model loaded successfully")
    except Exception as e:
        print(f"[API] Could not load model: {e}")


# ------------------------------------------------------------------ #
#  UTILITY
# ------------------------------------------------------------------ #

ACTION_NAMES = {0: "Do Nothing", 1: "Charge Battery", 2: "Discharge to House", 3: "Sell to Grid"}
ACTION_COLORS = {0: "#6c757d", 1: "#0d6efd", 2: "#198754", 3: "#ffc107"}


def _safe_float(v):
    if isinstance(v, (np.floating, np.integer)):
        return float(v)
    return v


def _serialise(obj):
    """Recursively convert numpy types to Python natives for JSON."""
    if isinstance(obj, dict):
        return {k: _serialise(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [_serialise(v) for v in obj]
    elif isinstance(obj, (np.floating, np.integer)):
        return float(obj)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    return obj


# ------------------------------------------------------------------ #
#  ROUTES
# ------------------------------------------------------------------ #

@app.route("/api/status", methods=["GET"])
def status():
    return jsonify({
        "status":       "running",
        "model_loaded": model_loaded,
        "model_path":   MODEL_PATH,
        "data_source":  "real" if data_path else "synthetic",
        "device":       str(agent.device),
        "epsilon":      round(agent.epsilon, 4),
        "total_steps":  agent.total_steps,
    })


@app.route("/api/run-episode", methods=["POST"])
def run_episode():
    """
    Run a full 24-hour episode with the DQN agent (or a specified agent).
    Body (optional JSON):
        {
            "agent": "dqn" | "rule" | "random" | "donothing",
            "seed": 42
        }
    """
    body       = request.get_json(silent=True) or {}
    agent_type = body.get("agent", "dqn")
    seed       = body.get("seed", None)

    # Pick agent
    if agent_type == "dqn":
        active_agent = agent
        greedy       = True
    elif agent_type == "rule":
        active_agent = RuleBasedAgent()
        greedy       = False
    elif agent_type == "random":
        active_agent = RandomAgent(seed=seed or 42)
        greedy       = False
    else:
        active_agent = DoNothingAgent()
        greedy       = False

    # Run episode
    if seed is not None:
        env.rng = np.random.default_rng(seed)

    state  = env.reset()
    done   = False
    steps  = []
    total_reward = 0.0

    while not done:
        try:
            action = active_agent.select_action(state, greedy=greedy)
        except TypeError:
            action = active_agent.select_action(state)

        q_values = agent.get_q_values(state) if agent_type == "dqn" else [0, 0, 0, 0]
        idx      = env.start_idx + env.current_step

        step_info = {
            "step":       env.current_step,
            "hour":       int(env.hours[idx]),
            "soc_before": round(float(state[0]), 3),
            "price":      round(float(env.prices[idx]), 2),
            "solar":      round(float(env.solar[idx]), 3),
            "load":       round(float(env.loads[idx]), 3),
            "action":     action,
            "action_name": ACTION_NAMES[action],
        }

        next_state, reward, done, info = env.step(action)
        step_info["reward"]    = round(float(reward), 4)
        step_info["soc_after"] = round(float(info["soc_after"]), 3)
        step_info["q_values"]  = [round(q, 3) for q in q_values]
        steps.append(step_info)

        total_reward += reward
        state         = next_state

    summary = env.get_episode_summary()

    return jsonify({
        "agent_type":     agent_type,
        "total_reward":   round(float(total_reward), 4),
        "steps":          steps,
        "action_counts":  summary["action_counts"],
    })


@app.route("/api/training-log", methods=["GET"])
def training_log():
    """Return training metrics from the saved log file."""
    if not os.path.exists(LOG_PATH):
        return jsonify({"error": "No training log found. Please train the model first."}), 404

    with open(LOG_PATH) as f:
        log = json.load(f)

    # Smooth rewards for chart display
    rewards = log.get("episode_rewards", [])
    window  = 20
    smoothed = []
    for i in range(len(rewards)):
        start = max(0, i - window + 1)
        smoothed.append(float(np.mean(rewards[start:i+1])))

    return jsonify({
        "episode_rewards":   [round(r, 4) for r in rewards],
        "smoothed_rewards":  [round(r, 4) for r in smoothed],
        "episode_losses":    [round(l, 6) for l in log.get("episode_losses", [])],
        "epsilons":          [round(e, 4) for e in log.get("epsilons", [])],
        "eval_episodes":     log.get("eval_episodes", []),
        "eval_dqn":          [round(r, 4) for r in log.get("eval_dqn", [])],
        "eval_rule":         [round(r, 4) for r in log.get("eval_rule", [])],
        "eval_random":       [round(r, 4) for r in log.get("eval_random", [])],
        "eval_donothing":    [round(r, 4) for r in log.get("eval_donothing", [])],
    })


@app.route("/api/compare", methods=["GET"])
def compare_agents():
    """Run all agents for N episodes and return comparison stats."""
    n = int(request.args.get("n", 30))

    agents = {
        "DQN (Trained)":  (agent,             True),
        "Rule-Based":     (RuleBasedAgent(),   False),
        "Random":         (RandomAgent(),      False),
        "Do-Nothing":     (DoNothingAgent(),   False),
    }

    results = {}
    for name, (ag, greedy) in agents.items():
        r = evaluate_agent(ag, env, n_episodes=n, greedy=greedy)
        results[name] = {
            "mean":  round(r["mean_reward"], 4),
            "std":   round(r["std_reward"],  4),
            "min":   round(r["min_reward"],  4),
            "max":   round(r["max_reward"],  4),
            "actions": r["action_counts"],
        }

    return jsonify(results)


@app.route("/api/custom-scenario", methods=["POST"])
def custom_scenario():
    """
    Run an episode with user-defined initial conditions.
    Body:
        {
            "initial_soc": 0.5,
            "agent": "dqn"
        }
    """
    body    = request.get_json(silent=True) or {}
    soc     = float(body.get("initial_soc", 0.5))
    ag_type = body.get("agent", "dqn")

    state = env.reset()
    env.battery_soc = np.clip(soc, 0.05, 0.95)

    # Delegate to run_episode logic
    request._cached_json = (body, True)
    return run_episode()


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    print(f"\n[API] Starting Smart Grid RL Backend on http://localhost:{port}")
    print(f"[API] Model loaded: {model_loaded}")
    app.run(debug=True, port=port)