# -*- coding: utf-8 -*-
"""baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RfGsiojgq1YLpRlDGnKr3UY29gq4IOKP
"""

"""
Baseline Comparison Methods
CT-469 Reinforcement Learning Project

Three baselines for comparing against DQN:
1. Rule-Based Agent   : Deterministic price-threshold heuristic
2. Random Agent       : Uniform random action selection
3. Do-Nothing Agent   : Always selects action 0 (no battery operation)

These baselines help demonstrate whether RL adds value beyond
simple engineering heuristics — a key requirement in the project brief.
"""

import numpy as np


class RuleBasedAgent:
    """
    Deterministic rule-based controller.

    Logic:
    - If price is LOW  (below mean) → Charge battery from grid
    - If price is HIGH (above mean) and battery > 20% → Sell to grid
    - If solar > load and battery not full → Charge from solar (Do Nothing effectively charges)
    - If battery > 50% and no solar → Discharge to house
    - Otherwise → Do Nothing

    This mirrors how a smart human homeowner might behave manually.
    It's a strong baseline because it uses domain knowledge.
    """

    def __init__(self, low_price_threshold: float = 0.4,
                 high_price_threshold: float = 0.7,
                 min_soc_to_sell: float = 0.2):
        """
        Args:
            low_price_threshold  : Normalised price below which charging is triggered [0,1]
            high_price_threshold : Normalised price above which selling is triggered [0,1]
            min_soc_to_sell      : Minimum SOC before agent will sell
        """
        self.low_price_threshold  = low_price_threshold
        self.high_price_threshold = high_price_threshold
        self.min_soc_to_sell      = min_soc_to_sell

    def select_action(self, state: np.ndarray) -> int:
        """
        State layout (matches SmartGridEnv):
            [0] battery_soc       (0.0 - 1.0)
            [1] grid_price_norm   (-3 to 3 standardised)
            [2] solar_norm        (0.0 - 1.0)
            [3] load_norm         (0.0 - 1.0)
            [4] hour_norm         (0.0 - 1.0)
            [5] day_norm          (0.0 - 1.0)
        """
        soc        = state[0]
        price_norm = state[1]   # Standardised (negative = cheap, positive = expensive)
        solar_norm = state[2]
        load_norm  = state[3]

        # Plenty of solar and battery not full → do nothing (solar auto-charges conceptually)
        if solar_norm > load_norm and soc < 0.9:
            return 1  # Charge

        # Price is high and battery has charge → sell back
        if price_norm > self.high_price_threshold and soc > self.min_soc_to_sell:
            return 3  # Sell

        # Price is low → charge from grid
        if price_norm < -self.low_price_threshold and soc < 0.9:
            return 1  # Charge

        # Battery has energy and house needs power → discharge
        if soc > 0.3 and solar_norm < load_norm:
            return 2  # Discharge

        return 0  # Do nothing


class RandomAgent:
    """
    Uniformly random action selection.
    Acts as a lower-bound baseline — any useful agent should beat this.
    """

    def __init__(self, action_dim: int = 4, seed: int = 42):
        self.action_dim = action_dim
        self.rng = np.random.default_rng(seed)

    def select_action(self, state: np.ndarray) -> int:
        return int(self.rng.integers(0, self.action_dim))


class DoNothingAgent:
    """
    Always takes action 0 (Do Nothing).
    Represents the baseline of having no battery management at all.
    """

    def select_action(self, state: np.ndarray) -> int:
        return 0


def evaluate_agent(agent, env, n_episodes: int = 50, greedy: bool = True) -> dict:
    """
    Run agent for n_episodes and collect performance statistics.

    Args:
        agent     : Any agent with a select_action(state) method
        env       : SmartGridEnv instance
        n_episodes: Number of evaluation episodes
        greedy    : If True, pass greedy=True to DQNAgent (ignored for baselines)

    Returns:
        Dictionary with mean/std/min/max total reward and action distribution
    """
    total_rewards = []
    all_action_counts = {"do_nothing": 0, "charge": 0, "discharge": 0, "sell": 0}
    action_names = ["do_nothing", "charge", "discharge", "sell"]

    for ep in range(n_episodes):
        state = env.reset()
        done  = False
        ep_reward = 0.0

        while not done:
            # Support both DQNAgent (has greedy kwarg) and simple agents
            try:
                action = agent.select_action(state, greedy=greedy)
            except TypeError:
                action = agent.select_action(state)

            state, reward, done, info = env.step(action)
            ep_reward += reward
            all_action_counts[action_names[action]] += 1

        total_rewards.append(ep_reward)

    return {
        "mean_reward":   float(np.mean(total_rewards)),
        "std_reward":    float(np.std(total_rewards)),
        "min_reward":    float(np.min(total_rewards)),
        "max_reward":    float(np.max(total_rewards)),
        "action_counts": all_action_counts,
        "all_rewards":   total_rewards,
    }