# -*- coding: utf-8 -*-
"""dqn_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x0N6n1R4IdiHyR_jgwV_1h2DoS0dgXSz
"""

"""
Deep Q-Network (DQN) Agent
CT-469 Reinforcement Learning Project

Implements DQN with:
- Experience Replay Buffer
- Target Network (updated every N steps)
- Epsilon-Greedy Exploration
- Neural network Q-function approximator
"""

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from collections import deque
import random
import os


# ------------------------------------------------------------------ #
#  NEURAL NETWORK: Q-FUNCTION APPROXIMATOR
# ------------------------------------------------------------------ #

class QNetwork(nn.Module):
    """
    Fully-connected neural network that maps (state) -> Q(s, a) for all actions.

    Architecture: Input(6) -> FC(128) -> ReLU -> FC(128) -> ReLU -> FC(64) -> ReLU -> Output(4)
    """

    def __init__(self, state_dim: int = 6, action_dim: int = 4, hidden: int = 128):
        super(QNetwork, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(state_dim, hidden),
            nn.ReLU(),
            nn.Linear(hidden, hidden),
            nn.ReLU(),
            nn.Linear(hidden, 64),
            nn.ReLU(),
            nn.Linear(64, action_dim)
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


# ------------------------------------------------------------------ #
#  EXPERIENCE REPLAY BUFFER
# ------------------------------------------------------------------ #

class ReplayBuffer:
    """
    Stores (state, action, reward, next_state, done) transitions.
    Supports uniform random sampling for DQN training.
    """

    def __init__(self, capacity: int = 50_000):
        self.buffer = deque(maxlen=capacity)

    def push(self, state, action, reward, next_state, done):
        self.buffer.append((
            np.array(state,      dtype=np.float32),
            int(action),
            float(reward),
            np.array(next_state, dtype=np.float32),
            float(done)
        ))

    def sample(self, batch_size: int):
        batch = random.sample(self.buffer, batch_size)
        states, actions, rewards, next_states, dones = zip(*batch)
        return (
            np.array(states),
            np.array(actions),
            np.array(rewards),
            np.array(next_states),
            np.array(dones)
        )

    def __len__(self):
        return len(self.buffer)


# ------------------------------------------------------------------ #
#  DQN AGENT
# ------------------------------------------------------------------ #

class DQNAgent:
    """
    DQN Agent with Experience Replay and Target Network.

    Key hyperparameters:
        gamma          : Discount factor for future rewards
        lr             : Learning rate for Adam optimiser
        epsilon_start  : Initial exploration rate
        epsilon_end    : Minimum exploration rate
        epsilon_decay  : Multiplicative decay per episode
        batch_size     : Minibatch size for gradient updates
        target_update  : Steps between target network syncs
        buffer_size    : Replay buffer capacity
    """

    def __init__(
        self,
        state_dim     : int   = 6,
        action_dim    : int   = 4,
        gamma         : float = 0.99,
        lr            : float = 1e-3,
        epsilon_start : float = 1.0,
        epsilon_end   : float = 0.05,
        epsilon_decay : float = 0.995,
        batch_size    : int   = 64,
        target_update : int   = 200,
        buffer_size   : int   = 50_000,
    ):
        self.state_dim    = state_dim
        self.action_dim   = action_dim
        self.gamma        = gamma
        self.lr           = lr
        self.epsilon      = epsilon_start
        self.epsilon_end  = epsilon_end
        self.epsilon_decay = epsilon_decay
        self.batch_size   = batch_size
        self.target_update = target_update

        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        print(f"[DQN] Using device: {self.device}")

        # Online network (trained every step)
        self.online_net = QNetwork(state_dim, action_dim).to(self.device)
        # Target network (periodically synced — stabilises training)
        self.target_net = QNetwork(state_dim, action_dim).to(self.device)
        self.target_net.load_state_dict(self.online_net.state_dict())
        self.target_net.eval()

        self.optimizer = optim.Adam(self.online_net.parameters(), lr=lr)
        self.loss_fn   = nn.MSELoss()
        self.buffer    = ReplayBuffer(buffer_size)

        self.total_steps  = 0
        self.train_losses = []

    # ---- ACTION SELECTION ----------------------------------------- #

    def select_action(self, state: np.ndarray, greedy: bool = False) -> int:
        """
        Epsilon-greedy action selection.
        - greedy=True: always pick best action (for evaluation)
        - greedy=False: explore with probability epsilon
        """
        if not greedy and random.random() < self.epsilon:
            return random.randint(0, self.action_dim - 1)

        state_tensor = torch.FloatTensor(state).unsqueeze(0).to(self.device)
        with torch.no_grad():
            q_values = self.online_net(state_tensor)
        return int(q_values.argmax(dim=1).item())

    # ---- TRAINING STEP -------------------------------------------- #

    def train_step(self) -> float:
        """
        Sample a minibatch from replay buffer and perform one gradient update.
        Returns the loss value.
        """
        if len(self.buffer) < self.batch_size:
            return 0.0

        states, actions, rewards, next_states, dones = self.buffer.sample(self.batch_size)

        # Convert to tensors
        states_t      = torch.FloatTensor(states).to(self.device)
        actions_t     = torch.LongTensor(actions).unsqueeze(1).to(self.device)
        rewards_t     = torch.FloatTensor(rewards).unsqueeze(1).to(self.device)
        next_states_t = torch.FloatTensor(next_states).to(self.device)
        dones_t       = torch.FloatTensor(dones).unsqueeze(1).to(self.device)

        # Current Q-values: Q(s, a) for the taken action
        current_q = self.online_net(states_t).gather(1, actions_t)

        # Target Q-values: r + γ * max_a' Q_target(s', a')
        with torch.no_grad():
            max_next_q = self.target_net(next_states_t).max(dim=1, keepdim=True)[0]
            target_q   = rewards_t + self.gamma * max_next_q * (1.0 - dones_t)

        # Bellman error / MSE loss
        loss = self.loss_fn(current_q, target_q)

        self.optimizer.zero_grad()
        loss.backward()
        # Gradient clipping for stability
        torch.nn.utils.clip_grad_norm_(self.online_net.parameters(), max_norm=1.0)
        self.optimizer.step()

        self.total_steps += 1

        # Sync target network every N steps
        if self.total_steps % self.target_update == 0:
            self.target_net.load_state_dict(self.online_net.state_dict())

        return loss.item()

    # ---- STORE TRANSITION ----------------------------------------- #

    def remember(self, state, action, reward, next_state, done):
        self.buffer.push(state, action, reward, next_state, done)

    # ---- EPSILON DECAY -------------------------------------------- #

    def decay_epsilon(self):
        self.epsilon = max(self.epsilon_end, self.epsilon * self.epsilon_decay)

    # ---- SAVE / LOAD ---------------------------------------------- #

    def save(self, path: str = "models/dqn_model.pth"):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        torch.save({
            "online_net":   self.online_net.state_dict(),
            "target_net":   self.target_net.state_dict(),
            "optimizer":    self.optimizer.state_dict(),
            "epsilon":      self.epsilon,
            "total_steps":  self.total_steps,
        }, path)
        print(f"[DQN] Model saved to {path}")

    def load(self, path: str = "models/dqn_model.pth"):
        if not os.path.exists(path):
            raise FileNotFoundError(f"Model file not found: {path}")
        checkpoint = torch.load(path, map_location=self.device)
        self.online_net.load_state_dict(checkpoint["online_net"])
        self.target_net.load_state_dict(checkpoint["target_net"])
        self.optimizer.load_state_dict(checkpoint["optimizer"])
        self.epsilon     = checkpoint.get("epsilon", self.epsilon_end)
        self.total_steps = checkpoint.get("total_steps", 0)
        self.online_net.eval()
        self.target_net.eval()
        print(f"[DQN] Model loaded from {path}")

    def get_q_values(self, state: np.ndarray) -> list:
        """Return Q-values for all actions given a state (for API / UI display)."""
        state_tensor = torch.FloatTensor(state).unsqueeze(0).to(self.device)
        with torch.no_grad():
            q_vals = self.online_net(state_tensor).squeeze(0).cpu().numpy()
        return q_vals.tolist()