# -*- coding: utf-8 -*-
"""environment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yun8g5ziaiJCU1R1WK-EupGyv3EC7Tx6
"""

"""
Smart Grid Energy Arbitrage Environment
CT-469 Reinforcement Learning Project

Custom OpenAI Gym-compatible environment that models a household with:
- Solar panels
- Battery storage
- Grid connection (buy/sell electricity)
"""

import numpy as np
import pandas as pd
import gymnasium as gym
from gymnasium import spaces


class SmartGridEnv(gym.Env):
    """
    Custom RL Environment for Smart Grid Energy Arbitrage.

    STATE SPACE (6 features):
        - battery_soc       : Battery State of Charge [0.0, 1.0]
        - grid_price        : Current electricity price (normalized)
        - solar_output      : Solar generation in kW (normalized)
        - house_load        : Household demand in kW (normalized)
        - hour_of_day       : Hour [0-23] (normalized)
        - day_of_week       : Day [0-6] (normalized)

    ACTION SPACE (4 discrete actions):
        - 0: Do Nothing
        - 1: Charge Battery from Grid
        - 2: Discharge Battery to House
        - 3: Sell Battery Power to Grid

    REWARD:
        profit = (cost_avoided + revenue_generated) - grid_purchase_cost - degradation_penalty
    """

    metadata = {"render.modes": ["human"]}

    # Battery configuration
    BATTERY_CAPACITY_KWH = 10.0     # 10 kWh battery
    CHARGE_RATE_KW       = 2.5      # Max charge/discharge per timestep (1 hour)
    BATTERY_EFFICIENCY   = 0.95     # Round-trip efficiency
    DEGRADATION_COST     = 0.002    # $ per kWh cycled (battery wear)

    # Sell-back rate multiplier (grid buys at 80% of market price)
    SELL_BACK_RATE       = 0.80

    def __init__(self, data_path: str = None, episode_length: int = 24, seed: int = 42):
        super(SmartGridEnv, self).__init__()

        self.episode_length = episode_length
        self.rng = np.random.default_rng(seed)

        # Load real dataset or generate synthetic data
        if data_path:
            self._load_real_data(data_path)
        else:
            self._generate_synthetic_data()

        # Normalisation stats (computed from dataset)
        self.price_mean  = np.mean(self.prices)
        self.price_std   = np.std(self.prices) + 1e-8
        self.solar_max   = np.max(self.solar) + 1e-8
        self.load_max    = np.max(self.loads) + 1e-8

        # Gym spaces
        self.observation_space = spaces.Box(
            low   = np.array([0.0, -3.0, 0.0, 0.0, 0.0, 0.0], dtype=np.float32),
            high  = np.array([1.0,  3.0, 1.0, 1.0, 1.0, 1.0], dtype=np.float32),
            dtype = np.float32
        )
        self.action_space = spaces.Discrete(4)

        # Episode state
        self.battery_soc   = 0.5   # Start at 50% charge
        self.current_step  = 0
        self.start_idx     = 0
        self.episode_reward = 0.0
        self.history       = []

# ------------------------------------------------------------------ #
       # DATA LOADING
# ------------------------------------------------------------------ #
    def _load_real_data(self, path: str):
        """Load the Kaggle ENTSO-E energy dataset with datetime fix."""
        import pandas as pd
        
        # 1. Load the data
        required_cols = ["time", "price day ahead", "generation solar", "total load actual"]
        df = pd.read_csv(path, usecols=required_cols)
        
        # 2. CRITICAL FIX: Convert the 'time' column to datetime objects
        # This fixes the "AttributeError: Can only use .dt accessor"
        df["time"] = pd.to_datetime(df["time"], utc=True)
        
        # 3. Clean and Sort
        df = df.dropna(subset=["price day ahead", "generation solar", "total load actual"])
        df = df.sort_values("time").reset_index(drop=True)

        # 4. Map to variables
        self.prices = df["price day ahead"].values.astype(np.float32)
        self.solar  = df["generation solar"].fillna(0).values.astype(np.float32)
        self.loads  = df["total load actual"].values.astype(np.float32)
        
        # 5. Extract time features (Now this will work!)
        self.hours  = df["time"].dt.hour.values.astype(np.float32)
        self.days   = df["time"].dt.dayofweek.values.astype(np.float32)
        
        self.n_timesteps = len(self.prices)
        print(f"[ENV] Loaded real dataset: {self.n_timesteps} hourly timesteps")

    def _generate_synthetic_data(self):
        """Generate realistic synthetic data if no dataset is provided."""
        n = 8760  # 1 year hourly
        hours = np.arange(n) % 24
        days  = (np.arange(n) // 24) % 7

        # Price: base + peak hours + noise
        price_base  = 50 + 20 * np.sin(2 * np.pi * hours / 24 - np.pi)
        price_noise = self.rng.normal(0, 5, n)
        prices      = np.clip(price_base + price_noise, 10, 150)

        # Solar: zero at night, bell curve during day
        solar_peak  = np.maximum(0, np.sin(np.pi * (hours - 6) / 12))
        solar_noise = self.rng.uniform(0.8, 1.2, n)
        solar       = solar_peak * solar_noise * 5.0  # max 5 kW

        # Load: morning + evening peaks
        load_base   = 2.0 + 1.5 * (np.exp(-((hours - 8) ** 2) / 8) +
                                    np.exp(-((hours - 19) ** 2) / 8))
        load_noise  = self.rng.normal(0, 0.2, n)
        loads       = np.clip(load_base + load_noise, 0.5, 6.0)

        self.prices       = prices.astype(np.float32)
        self.solar        = solar.astype(np.float32)
        self.loads        = loads.astype(np.float32)
        self.hours        = hours.astype(np.float32)
        self.days         = days.astype(np.float32)
        self.n_timesteps  = n
        print(f"[ENV] Generated synthetic dataset: {self.n_timesteps} timesteps")

    # ------------------------------------------------------------------ #
    #  GYM INTERFACE
    # ------------------------------------------------------------------ #

    def _get_obs(self) -> np.ndarray:
        idx = self.start_idx + self.current_step
        obs = np.array([
            self.battery_soc,
            (self.prices[idx] - self.price_mean) / self.price_std,
            self.solar[idx]  / self.solar_max,
            self.loads[idx]  / self.load_max,
            self.hours[idx]  / 23.0,
            self.days[idx]   / 6.0,
        ], dtype=np.float32)
        return obs

    def reset(self):
        # Start from a random hour in the dataset (minus episode_length buffer)
        max_start = self.n_timesteps - self.episode_length - 1
        self.start_idx    = int(self.rng.integers(0, max_start))
        self.battery_soc  = float(self.rng.uniform(0.2, 0.8))
        self.current_step = 0
        self.episode_reward = 0.0
        self.history      = []
        return self._get_obs()

    def step(self, action: int):
        idx   = self.start_idx + self.current_step
        price = self.prices[idx]   # $/MWh → convert to $/kWh below
        price_kwh  = price / 1000.0   # if dataset is in $/MWh
        solar_kw   = self.solar[idx]
        load_kw    = self.loads[idx]

        # Net solar surplus (positive = excess, negative = deficit)
        net_solar  = solar_kw - load_kw

        reward     = 0.0
        info       = {"action": action, "price": price_kwh,
                      "solar": solar_kw, "load": load_kw,
                      "soc_before": self.battery_soc}

        # --- ACTION EXECUTION ---
        if action == 0:  # Do Nothing
            if net_solar > 0:
                # Free solar covers load; excess is wasted
                reward = net_solar * price_kwh  # opportunity cost saved
            else:
                # Buy deficit from grid
                grid_buy = -net_solar
                reward   = -grid_buy * price_kwh

        elif action == 1:  # Charge Battery from Grid
            charge_kwh = min(self.CHARGE_RATE_KW,
                             self.BATTERY_CAPACITY_KWH * (1.0 - self.battery_soc))
            # Also cover house load from grid
            total_grid_purchase = charge_kwh + max(0, -net_solar)
            self.battery_soc   += (charge_kwh * self.BATTERY_EFFICIENCY) / self.BATTERY_CAPACITY_KWH
            self.battery_soc    = np.clip(self.battery_soc, 0.0, 1.0)
            degradation         = charge_kwh * self.DEGRADATION_COST
            reward = -total_grid_purchase * price_kwh - degradation
            info["charged_kwh"] = charge_kwh

        elif action == 2:  # Discharge Battery to House
            discharge_kwh = min(self.CHARGE_RATE_KW,
                                self.battery_soc * self.BATTERY_CAPACITY_KWH)
            cost_avoided   = min(discharge_kwh, max(0, -net_solar)) * price_kwh
            self.battery_soc  -= discharge_kwh / self.BATTERY_CAPACITY_KWH
            self.battery_soc   = np.clip(self.battery_soc, 0.0, 1.0)
            degradation        = discharge_kwh * self.DEGRADATION_COST
            # Remaining load deficit (if battery didn't cover all)
            remaining_deficit  = max(0, (-net_solar) - discharge_kwh)
            reward = cost_avoided - remaining_deficit * price_kwh - degradation
            info["discharged_kwh"] = discharge_kwh

        elif action == 3:  # Sell Battery Power to Grid
            sell_kwh  = min(self.CHARGE_RATE_KW,
                            self.battery_soc * self.BATTERY_CAPACITY_KWH)
            revenue   = sell_kwh * price_kwh * self.SELL_BACK_RATE
            self.battery_soc -= sell_kwh / self.BATTERY_CAPACITY_KWH
            self.battery_soc  = np.clip(self.battery_soc, 0.0, 1.0)
            degradation        = sell_kwh * self.DEGRADATION_COST
            # Still need to cover house load from grid if solar insufficient
            grid_buy_for_load  = max(0, (-net_solar)) * price_kwh
            reward = revenue - grid_buy_for_load - degradation
            info["sold_kwh"] = sell_kwh

        self.episode_reward += reward
        info["soc_after"]    = self.battery_soc
        info["reward"]       = reward
        self.history.append(info)

        self.current_step += 1
        done = (self.current_step >= self.episode_length)
        obs  = self._get_obs() if not done else np.zeros(6, dtype=np.float32)

        return obs, reward, done, info

    def render(self, mode="human"):
        idx = self.start_idx + self.current_step
        print(f"Step {self.current_step:3d} | "
              f"SOC: {self.battery_soc:.2f} | "
              f"Price: {self.prices[idx]:.1f} | "
              f"Solar: {self.solar[idx]:.2f} kW | "
              f"Load: {self.loads[idx]:.2f} kW | "
              f"Total Reward: {self.episode_reward:.4f}")

    def get_episode_summary(self) -> dict:
        """Return summary stats for the completed episode."""
        rewards = [h["reward"] for h in self.history]
        actions = [h["action"] for h in self.history]
        return {
            "total_reward": sum(rewards),
            "mean_reward":  np.mean(rewards),
            "action_counts": {
                "do_nothing": actions.count(0),
                "charge":     actions.count(1),
                "discharge":  actions.count(2),
                "sell":       actions.count(3),
            },
            "history": self.history,
        }