# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NeM51k6bQQ6ywG6cXUS__r_lYn1HOnbo
"""

"""
Training Script — Smart Grid DQN Agent
CT-469 Reinforcement Learning Project

Run this script to train the DQN agent from scratch.
Usage:
    python train.py
    python train.py --episodes 500 --data data/energy_dataset.csv

Training metrics are saved to logs/training_log.json for visualisation.
Model weights are saved to models/dqn_model.pth
"""

import argparse
import json
import os
import time
import numpy as np

from environment import SmartGridEnv
from dqn_agent   import DQNAgent
from baseline    import RuleBasedAgent, RandomAgent, DoNothingAgent, evaluate_agent


def parse_args():
    parser = argparse.ArgumentParser(description="Train DQN Agent for Smart Grid")
    parser.add_argument("--episodes",    type=int,   default=300,  help="Number of training episodes")
    parser.add_argument("--ep_length",   type=int,   default=24,   help="Timesteps per episode (hours)")
    parser.add_argument("--data",        type=str,   default=None, help="Path to CSV dataset")
    parser.add_argument("--seed",        type=int,   default=42)
    parser.add_argument("--eval_every",  type=int,   default=50,   help="Evaluate every N episodes")
    parser.add_argument("--model_path",  type=str,   default="models/dqn_model.pth")
    parser.add_argument("--log_path",    type=str,   default="logs/training_log.json")
    return parser.parse_args()


def train(args):
    os.makedirs("models", exist_ok=True)
    os.makedirs("logs",   exist_ok=True)

    print("=" * 60)
    print("  CT-469 Smart Grid RL — DQN Training")
    print("=" * 60)

    # ---- ENVIRONMENT -----------------------------------------------
    env = SmartGridEnv(
        data_path      = args.data,
        episode_length = args.ep_length,
        seed           = args.seed,
    )

    # ---- AGENT -----------------------------------------------------
    agent = DQNAgent(
        state_dim      = env.observation_space.shape[0],
        action_dim     = env.action_space.n,
        gamma          = 0.99,
        lr             = 1e-3,
        epsilon_start  = 1.0,
        epsilon_end    = 0.05,
        epsilon_decay  = 0.995,
        batch_size     = 64,
        target_update  = 200,
        buffer_size    = 50_000,
    )

    # ---- LOGGING ---------------------------------------------------
    log = {
        "episode_rewards":    [],
        "episode_losses":     [],
        "epsilons":           [],
        "eval_dqn":           [],
        "eval_rule":          [],
        "eval_random":        [],
        "eval_donothing":     [],
        "eval_episodes":      [],
    }

    best_reward = -np.inf
    start_time  = time.time()

    print(f"\nTraining for {args.episodes} episodes...\n")

    # ---- TRAINING LOOP ---------------------------------------------
    for episode in range(1, args.episodes + 1):
        state     = env.reset()
        done      = False
        ep_reward = 0.0
        ep_losses = []

        while not done:
            action                    = agent.select_action(state)
            next_state, reward, done, _ = env.step(action)
            agent.remember(state, action, reward, next_state, done)
            loss = agent.train_step()
            if loss > 0:
                ep_losses.append(loss)
            state      = next_state
            ep_reward += reward

        agent.decay_epsilon()

        log["episode_rewards"].append(ep_reward)
        log["episode_losses"].append(float(np.mean(ep_losses)) if ep_losses else 0.0)
        log["epsilons"].append(agent.epsilon)

        # Save best model
        if ep_reward > best_reward:
            best_reward = ep_reward
            agent.save(args.model_path)

        # Progress print
        if episode % 10 == 0:
            avg_r = np.mean(log["episode_rewards"][-10:])
            print(f"Episode {episode:4d}/{args.episodes} | "
                  f"Avg Reward (last 10): {avg_r:8.4f} | "
                  f"Epsilon: {agent.epsilon:.3f} | "
                  f"Buffer: {len(agent.buffer):6d} | "
                  f"Time: {time.time()-start_time:.0f}s")

        # Evaluation against baselines
        if episode % args.eval_every == 0:
            print(f"\n  ---- Evaluating at episode {episode} ----")
            agent.load(args.model_path)  # Load best so far

            rule_agent     = RuleBasedAgent()
            random_agent   = RandomAgent(seed=args.seed)
            nothing_agent  = DoNothingAgent()

            dqn_result    = evaluate_agent(agent,        env, n_episodes=20, greedy=True)
            rule_result   = evaluate_agent(rule_agent,   env, n_episodes=20)
            rand_result   = evaluate_agent(random_agent, env, n_episodes=20)
            noth_result   = evaluate_agent(nothing_agent,env, n_episodes=20)

            log["eval_dqn"].append(dqn_result["mean_reward"])
            log["eval_rule"].append(rule_result["mean_reward"])
            log["eval_random"].append(rand_result["mean_reward"])
            log["eval_donothing"].append(noth_result["mean_reward"])
            log["eval_episodes"].append(episode)

            print(f"  DQN:        {dqn_result['mean_reward']:.4f} ± {dqn_result['std_reward']:.4f}")
            print(f"  Rule-Based: {rule_result['mean_reward']:.4f} ± {rule_result['std_reward']:.4f}")
            print(f"  Random:     {rand_result['mean_reward']:.4f}")
            print(f"  Do-Nothing: {noth_result['mean_reward']:.4f}\n")

    # ---- FINAL SAVE ------------------------------------------------
    elapsed = time.time() - start_time
    print(f"\nTraining complete in {elapsed:.1f}s")
    print(f"Best reward: {best_reward:.4f}")
    print(f"Model saved: {args.model_path}")

    with open(args.log_path, "w") as f:
        json.dump(log, f, indent=2)
    print(f"Training log saved: {args.log_path}")

    return log


if __name__ == "__main__":
    args = parse_args()
    train(args)